config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossips do
    resources :comments, only: [:show]
  end
  resources :users, only: [:show] do
    resources :private_messages, only: [:show]
  end
  resources :cities, only: [:show]
  resources :tags, only: [:show]
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get 'welcome/:first_name', to: 'welcome#show'
  root 'gossips#index'
  get '/', to: 'gossips#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :description,
            length: { minimum: 140 },
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Recheck your email adress please!" }
  validates :age,
            numericality: { only_integer: true, greater_than: 13 },
            presence: true
  belongs_to :city
  has_many :gossips, foreign_key: 'author_id', class_name: "Gossip"
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_recipient_pms, foreign_key: :recipient_id, class_name: "JoinTableRecipientPm"
  has_many :received_messages, through: :join_table_recipient_pms
  has_many :comments, foreign_key: 'author_id', class_name: "Comment"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    puts "$" * 60
    puts "Voici le nombre d'utilisateurs dans la base : #{@users.length}"
    puts "$" * 60
  end

  def show
    @user_hash = get_user_hash
  end

  private

  def get_user_hash
    @user_hash = { "user" => nil, "index" => -1 }
    user_id = params[:id].to_i
    user = nil
    puts "$" * 60
    puts "user_id : #{user_id}"
    if user_id.between?(1, User.count)
      user = User.find(user_id)
      puts "user : #{user}"
    end
    @user_hash = { "user" => user, "index" => user_id }
    puts "user_hash : #{@user_hash}"
    puts "$" * 60
    @user_hash 
  end
end

app/views/users/show.html.erb
<% if !@user_hash['user'].nil? %>
  <h1>Voici la page profil de l'auteur de potins n°<%= @user_hash['index'] %></h1>
  <div>
    <p>Son prénom : <%= @user_hash['user'].first_name %></p>
    <p>Son nom : <%= @user_hash['user'].last_name %></p>
    <p>Son email : <%= @user_hash['user'].email %></p>
    <p>Son age : <%= @user_hash['user'].age %></p>
    <p>Sa ville : <%= @user_hash['user'].city.name %> (<%= @user_hash['user'].city.zip_code %>)</p>
  </div>
<% else %>
  <div class="alert alert-danger" role="alert">
    <p>Aucun utilisateur de n°<%= @user_hash['index'] %> n'existe dans la base!</p>
  </div>
<% end %>
<div>
  <p>
    <a href="<%= gossips_path %>" class="btn btn-primary btn-sm" role="button">Revenir à la liste des potins</a>
  </p>
</div>