config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gossips do
    resources :comments, only: [:show]
  end
  resources :users, only: [:show] do
    resources :private_messages, only: [:show]
  end
  resources :cities, only: [:show]
  resources :tags, only: [:show]
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get 'welcome/:first_name', to: 'welcome#show'
  root 'gossips#index'
  get '/', to: 'gossips#index'
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
            length: { minimum: 3, maximum: 14 },
            presence: true
  validates :content,
            presence: true
  belongs_to :author, class_name: "User"
  has_many :comments
  has_many :join_table_tag_gossips, foreign_key: :gossip_id, class_name: "JoinTableTagGossip"
  has_many :tags, through: :join_table_tag_gossips
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  ANONYMOUS_USER_ID = 1.freeze # Ruby Freeze method basically make object constant or immutable

  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    @gossips = Gossip.all
    puts "$" * 60
    puts "Voici le nombre de potins dans la base : #{@gossips.length}"
    puts "$" * 60
  end

  def show
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    @gossip_hash = get_gossip_hash 
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @new_gossip = Gossip.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une création"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans le champ title : #{params["title"]}"
    puts "De la bombe, et du coup ça, ça doit être ce que l'utilisateur a passé dans le champ content : #{params["content"]}"
    @gossip = Gossip.new("title" => params[:title],
                         "content" => params[:content],
                         "author" => User.find(ANONYMOUS_USER_ID))
    if @gossip.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      #redirect_to action: :index
      redirect_to gossips_path, status: :ok, notice: 'Ton super potin a bien été créé en base pour la postérité !'
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end
    puts "$" * 60
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    @gossip_hash = get_gossip_hash 
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une mise à jour"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans le champ title : #{params["title"]}"
    puts "De la bombe, et du coup ça, ça doit être ce que l'utilisateur a passé dans le champ content : #{params["content"]}"
    ok = false
    @gossip = Gossip.find(params[:id])
    @gossip_hash = { "gossip" => @gossip, "index" => params[:id] }
    puts "gossip_hash : #{@gossip_hash}"
    if !params[:title].nil? && !params[:content].nil?
      gossip_saved = @gossip.update("title" => params[:title], # essaie de sauvegarder en base gossip
                                    "content" => params[:content],
                                    "author" => User.find(ANONYMOUS_USER_ID))
      if gossip_saved
        # si ça a marché, il redirige vers la méthode index
        ok = true
        @gossip = Gossip.find(params[:id])
        @gossip_hash = { "gossip" => @gossip, "index" => params[:id] }
        puts "gossip_hash : #{@gossip_hash}"
        redirect_to gossips_path, status: :ok, notice: 'Ton super potin a bien été mis à jour en base : il est bien plus "dévastateur" désormais !'
      end
    end
    if !ok
      # sinon, il render la view edit (qui est celle sur laquelle on est déjà)
      render 'edit'
    end
    puts "$" * 60
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    puts "$" * 60
    puts "Salut, je suis dans le serveur pour une suppression"
    puts "Ceci est le contenu du hash params : #{params}"
    puts "gossip_id : #{params[:id]}"
    @gossip_hash = get_gossip_hash 
    if !@gossip_hash['gossip'].nil?
      @gossip_hash['gossip'].destroy
      redirect_to gossips_path, status: :ok, notice: 'Ton "sale petit" potin a bien été supprimé en base : plus personne ne saura que tu as un jour osé le proférer !'
    end
    puts "$" * 60
  end

  private

  def get_gossip_hash
    @gossip_hash = { "gossip" => nil, "index" => -1 }
    gossip_id = params[:id].to_i
    gossip = nil
    puts "$" * 60
    puts "gossip_id : #{gossip_id}"
    nb_total = Gossip.last.id
    if gossip_id.between?(1, nb_total)
      gossip = Gossip.find_by(id: gossip_id)
    end
    @gossip_hash = { "gossip" => gossip, "index" => gossip_id }
    puts "gossip_hash : #{@gossip_hash}"
    puts "$" * 60
    @gossip_hash
  end
end

app/views/gossips/edit.html.erb
<% if !@gossip_hash['gossip'].nil? %>
  
  <h1>Modifie ton potin n°<%= @gossip_hash['index'] %></h1>

  <% if !@gossip.nil? && @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>Nous n'avons pas réussi à mettre à jour le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form_tag gossip_path(@gossip_hash['index']), method: "post" do %>

    <input type="hidden" name ="_method" value="put">

    <%= label_tag 'Titre' %>
    <%= text_field_tag 'title', (@gossip_hash['gossip'].title if !@gossip_hash['gossip'].title.nil?), size: 20, maxlength: 14 %>
    <br /> <br />
    
    <%= label_tag 'Contenu' %>
    <%= text_area_tag 'content', (@gossip_hash['gossip'].content if !@gossip_hash['gossip'].content.nil?), size: "25x10" %>
    <br /> <br />
    
    <%= submit_tag "Enregistrer cette nouvelle version de ton potin" %>

  <% end %>

<% else %>

  <div class="alert alert-danger" role="alert">
    <p>Aucun potin de n°<%= @gossip_hash['index'] %> n'existe dans la base!</p>
  </div>

<% end %>

app/views/gossips/index.html.erb
<style type="text/css">
  table {
    margin:auto;
  }
  table,
  td {
    border: 1px solid #333;
  }

  thead,
  tfoot {
    background-color: #333;
    color: #fff;
  }
</style>

<div>
  <h1>Bienvenue sur l'application de la communauté de <em>"The Hacking Project"</em></h1>
  <p>Il se passe plein de choses à Paris, Lyon, Montpellier, Bordeaux et ce site va te permettre de connaître tous les potins sur tes camarades moussaillons.</p>
  <BR>
  <% if !notice.nil? %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  <table>
    <caption>Voici la liste des potins qui circulent...</caption>
    <thead>
      <tr>
        <th>Prénom de l'auteur</th>
        <th>Titre</th>
        <th>Page</th>
      </tr>
    </thead>
    <tbody>
      <% @gossips.each do |gossip| %>
        <tr>
          <td><%= gossip.author.first_name %></td>
          <td><%= gossip.title %></td>
          <td><%= link_to "Potin n°#{gossip.id}", gossip_path(gossip.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div><BR>
<div>
  <p><a href="<%= new_gossip_path %>" class="btn btn-primary btn-sm" role="button">Ajoute un nouveau potin à la base</a></p>
</div>

app/views/gossips/new.html.erb
<h1>Crée un potin !</h1>
<p>Balance ton potin via le formulaire ci-dessous</p>

<% if !@gossip.nil? && @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title', (@gossip.title if !@gossip.nil?), size: 20, maxlength: 14 %>
  <br /> <br />

  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'content', (@gossip.content if !@gossip.nil?), size: "25x10" %>
  <br /> <br />

  <%= submit_tag "Enregistrer ce potin" %>

<% end %>

app/views/gossips/show.html.erb
<style type="text/css">
  .content {
    font-style: italic;
    border-radius: 10px !important;
    text-indent: 12px !important;
    width: auto !important;
    padding: 0px 8px !important;
    text-align: center !important;
    vertical-align: middle !important;
    font: bold 11px / 20px &quot;Helvetica Neue&quot;, Helvetica, sans-serif !important;
    --color: rgb(255, 255, 255) !important;
    }
</style>

<% if !@gossip_hash['gossip'].nil? %>
  <h1>Voici la page du potin n°<%= @gossip_hash['index'] %></h1>
  <div>
    <p class="author">Son auteur : <em><%= link_to "#{@gossip_hash['gossip'].author.first_name} #{@gossip_hash['gossip'].author.last_name}", user_path(@gossip_hash['gossip'].author.id) %></em></p>
    <p>Son titre : <%= @gossip_hash['gossip'].title %></p>
    <p>Le contenu du potin : <p class="content"><%= @gossip_hash['gossip'].content %></p></p>
    <p>La date de création du potin : <%= @gossip_hash['gossip'].created_at %></p>
    <p>La date de dernière modification du potin : <%= @gossip_hash['gossip'].updated_at %></p>
    <br />
    <p>
      <a href="<%= edit_gossip_path(@gossip_hash['index']) %>" class="btn btn-primary btn-sm" role="button">Modifier le potin</a><span>
      <a href="<%= gossip_path(@gossip_hash['index']) %>" class="btn btn-danger btn-sm" role="button" data-confirm="Êtes-vous certain de vouloir supprimer définitivement ce potin?" data-method="DELETE">Supprimer le potin</a>
    </p>
  </div>
<% else %>
  <div class="alert alert-danger" role="alert">
    <p>Aucun potin de n°<%= @gossip_hash['index'] %> n'existe dans la base!</p>
  </div>
<% end %>
<div>
  <p>
    <a href="<%= gossips_path %>" class="btn btn-primary btn-sm" role="button">Revenir à la liste des potins</a>
  </p>
</div>